In [1]:
import pandas as pd
import numpy as np

In [2]:
pd.__version__

'1.3.4'

In [3]:
df = pd.read_csv('https://raw.githubusercontent.com/alexeygrigorev/datasets/master/housing.csv')

In [18]:
df.head()

longitude  latitude  housing_median_age  total_rooms  total_bedrooms  \
0    -122.23     37.88                41.0        880.0           129.0   
1    -122.22     37.86                21.0       7099.0          1106.0   
2    -122.24     37.85                52.0       1467.0           190.0   
3    -122.25     37.85                52.0       1274.0           235.0   
4    -122.25     37.85                52.0       1627.0           280.0   

   population  households  median_income  median_house_value ocean_proximity  
0       322.0       126.0         8.3252            452600.0        NEAR BAY  
1      2401.0      1138.0         8.3014            358500.0        NEAR BAY  
2       496.0       177.0         7.2574            352100.0        NEAR BAY  
3       558.0       219.0         5.6431            341300.0        NEAR BAY  
4       565.0       259.0         3.8462            342200.0        NEAR BAY

In [5]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 20640 entries, 0 to 20639
Data columns (total 10 columns):
 #   Column              Non-Null Count  Dtype  
---  ------              --------------  -----  
 0   longitude           20640 non-null  float64
 1   latitude            20640 non-null  float64
 2   housing_median_age  20640 non-null  float64
 3   total_rooms         20640 non-null  float64
 4   total_bedrooms      20433 non-null  float64
 5   population          20640 non-null  float64
 6   households          20640 non-null  float64
 7   median_income       20640 non-null  float64
 8   median_house_value  20640 non-null  float64
 9   ocean_proximity     20640 non-null  object 
dtypes: float64(9), object(1)
memory usage: 1.6+ MB


In [11]:
df.ocean_proximity.nunique()

5

In [12]:
df.median_house_value.mean()

206855.81690891474

In [13]:
df.total_bedrooms.mean()

537.8705525375618

In [15]:
mean_value = df.total_bedrooms.mean()

In [16]:
df['total_bedrooms'].fillna(value=mean_value, inplace=True)

In [17]:
df.total_bedrooms.mean()

537.8705525375639

In [19]:
df.ocean_proximity.unique()

array(['NEAR BAY', '<1H OCEAN', 'INLAND', 'NEAR OCEAN', 'ISLAND'],
      dtype=object)

In [25]:
x = df.query('ocean_proximity == "ISLAND"')[['housing_median_age', 'total_rooms', 'total_bedrooms']].to_numpy()

In [32]:
df.query('ocean_proximity == "ISLAND"')[['housing_median_age', 'total_rooms', 'total_bedrooms']]

housing_median_age  total_rooms  total_bedrooms
8314                27.0       1675.0           521.0
8315                52.0       2359.0           591.0
8316                52.0       2127.0           512.0
8317                52.0        996.0           264.0
8318                29.0        716.0           214.0

In [26]:
x

array([[  27., 1675.,  521.],
       [  52., 2359.,  591.],
       [  52., 2127.,  512.],
       [  52.,  996.,  264.],
       [  29.,  716.,  214.]])

In [79]:
def vector_vector_multiplication(u, v):
    assert u.shape[0] == v.shape[0]
    
    n = u.shape[0]
    
    result = 0.0

    for i in range(n):
        result = result + u[i] * v[i]
    
    return result

In [80]:
def matrix_vector_multiplication(U, v):
    assert U.shape[1] == v.shape[0]
    
    num_rows = U.shape[0]
    
    result = np.zeros(num_rows)
    
    for i in range(num_rows):
        result[i] = vector_vector_multiplication(U[i], v)
    
    return result

In [81]:
def matrix_matrix_multiplication(U, V):
    assert U.shape[1] == V.shape[0]
    
    num_rows = U.shape[0]
    num_cols = V.shape[1]
    
    result = np.zeros((num_rows, num_cols))
    
    for i in range(num_cols):
        vi = V[:, i]
        Uvi = matrix_vector_multiplication(U, vi)
        result[:, i] = Uvi
    
    return result

In [44]:
xtx = matrix_matrix_multiplication(x, x.T)

In [46]:
inverse = np.linalg.inv(xtx)

In [47]:
y = np.array([950, 1300, 800, 1000, 1300])

In [48]:
y

array([ 950, 1300,  800, 1000, 1300])

In [49]:
xtx

array([[3077795., 4260640., 3830881., 1807248., 1311577.],
       [4260640., 5916866., 5322889., 2508292., 1817026.],
       [3830881., 5322889., 4788977., 2256364., 1634008.],
       [1807248., 2508292., 2256364., 1064416.,  771140.],
       [1311577., 1817026., 1634008.,  771140.,  559293.]])

In [52]:
inverse

array([[-4.96451131e+09,  4.33221055e+09, -2.49341246e+09,
        -8.51337321e+09,  1.65903349e+10],
       [ 3.47335696e+09, -2.29339754e+09,  9.48896957e+08,
         6.38081159e+09, -1.22644417e+10],
       [-1.56701185e+09,  5.71843480e+08,  7.11310019e+07,
        -3.14511205e+09,  5.94553357e+09],
       [-9.00771614e+09,  8.28499475e+09, -4.98202900e+09,
        -1.52024896e+10,  2.97235715e+10],
       [ 1.73556241e+10, -1.58023656e+10,  9.42573071e+09,
         2.93839365e+10, -5.74131564e+10]])

In [64]:
xt = x.T

In [93]:
xt = np.pad(xt, ((0,2), (0,0)), mode='constant', constant_values=0)

In [95]:
w1 = matrix_matrix_multiplication(inverse, xt)

In [96]:
w = matrix_vector_multiplication(w1, y)

In [97]:
w

array([ 2.92603986e+16, -1.61220982e+16,  4.54418144e+15,  5.55942403e+16,
       -1.06168262e+17])